############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
hasChildren = true
weight = 3

[[main]]
parent = "Blog"
name = "Categories"
url = "categories/"
weight = 1

[[main]]
parent = "Blog"
name = "Posts"
url = "blog/"
weight = 2


# references
[[main]]
name = "References"
hasChildren = true
weight = 4

[[main]]
parent = "References"
name = "Contact"
url = "contact/"

[[main]]
parent = "References"
name = "Authors"
url = "authors/"

[[main]]
parent = "References"
name = "404 Page"
url = "404/"

[[main]]
parent = "References"
name = "Elements"
url = "elements/"



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
